### ISSUE TITLE
File->Load from Computer didn't work but dragging did

### ISSUE THREAD

**Issue by ctrager** [pkalogiros/AudioMass#5]
I cloned repo locally and tried loading an mp3 file using the menu File->Load from Computer. Nothing happened. I tried dragging it and it worked fine.

I tested this in Chrome. I didn't see any errors in developer javascript console.

**Comment by pkalogiros** [comment]
This is fixed in - https://github.com/pkalogiros/AudioMass/commit/2c9c043

For some reason mp3 audio file's content type now shows up as audio/mpeg instead of audio/mp3

This used to work, so not sure if this is a chrome bug, or what used to work was the bug.
In any case, it should be fixed and on master!

**Comment by pkalogiros** [comment]
Will be closing this! Feel free to re-open if things are not right :)
